### ISSUE TITLE
Windows installer that bundle Python

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/brutalmaze#3]
[pynsist](https://pynsist.readthedocs.io/en/latest/) doesn't seem to generate valid [EXE installer](https://github.com/McSinyx/brutalmaze/releases/tag/0.2.2) using the [current config](https://github.com/McSinyx/brutalmaze/commit/7cb264ee7887b775b45cec623c89c337c90e79b6#diff-40e175c2c5bf3c7e711b67ef98472495). While `pynsist` does run natively on GNU/Linux, the EXE file doesn't work on `wine` so I need help from someone using Windows here.

**Comment by McSinyx** [comment]
@t-rekttt Are you interested? After researching for a while, I found these *possible* solutions:

* pynsist, as described above
* py2exe
* `setup.py bdist_wininst`, in this case user will still need to manually install Python though

As Python 2 will retire around 2020, please make sure the installer builder runs well in Python 3. I'd be very grateful if you spend some time helping me on this.

**Comment by t-rekttt** [comment]
Suggest py2exe. Used it and it's awesome. It contains everything needed for your software to run and no installer or Python version needed.

**Comment by McSinyx** [comment]
Same for other suggestion I stated above, also I think I forgot to mention py2exe is no longer maintained. What I tried to say was that could you please help (means research and write installer builder) me on this because I don't have Windows on my machine. Thanks in advance.

Edit: no need to rush, and enjoy your holiday :fireworks:

**Comment by McSinyx** [comment]
I no longer want to support this.  If somebody wants to file a PR for it, feel free to comment below and I'll reopen the issue.
